### PR TITLE
Add a dockerfile to build mobile app

### PR DESCRIPTION
**Pull request by dolph**
Step 4 of the journey took me several hours to successfully complete the
first time on a fresh Ubuntu install. I made several mistakes during in
the process, including installing the wrong versions of dependencies
(installing an older version of node.js + npm from apt packaging, for
example), incorrectly configuring environment variables (I set *both*
JAVA_HOME and ANDROID_HOME incorrectly at some point).

This dockerfile provides a complete alternative to step 4, by packaging
the mobile app's development environment in a reproducible manner. The
only requirement is that Docker itself be installed.

All cordova commands (like `cordova build android`), can be executed via
docker in the container, and the resulting APK will appear on the host
filesystem. For example:

    $ docker run -v mobile:/mobile `docker build --quiet .`

### CODE REVIEW

**Comment by RiyaMRoy04** [comment]
Great! @dolph Please update the README with dockerfile after @rhagarty reviews the changes!

**Comment by dolph** [comment]
This definitely needs additional documentation prior to merging, and preferably some CI support, but I wanted to get it up for early discussion.

**Comment by dolph** [comment]
Coincidentally, this also eliminates the need for Android Studio (and therefore a GUI), although developers are still free to use Android Studio outside the docker container if that's their desired IDE.

**Comment by dolph** [comment]
Added lots of doc revisions in the patch above, but the result will conflict pretty heavily with PR #24, so I tried to keep the editing relatively conservative.

**Comment by stevemart** [comment]
lots of good in this PR @dolph +1

**Pull request merged**
